### ISSUE TITLE
insert_default_data.sql

### ISSUE THREAD

**Issue by frostieDE** [FPfotenhauer/Schild-NRW-DB-Scripte#15]
Die SQL-Datei zum Einfügen von Dummy-Daten lässt sich weder mit MSSQL noch mit MariaDB importieren, da Zeichenketten nicht sauber als solche deklariert sind (es fehlen die Anführungszeichen).

**Comment by frostieDE** [comment]
Screenshot von MySQL Workbench:

![grafik](https://user-images.githubusercontent.com/3764924/70659324-30d62480-1c60-11ea-962f-7f8c42d5dd30.png)

**Comment by FPfotenhauer** [comment]
Ist in den aktuellen Scripten behoben.
