### ISSUE TITLE
Revisionen

### ISSUE THREAD

**Issue by frostieDE** [FPfotenhauer/Schild-NRW-DB-Scripte#17]
Anstelle von Unterordnern **bitte unbedingt** Tags von Git genutzt werden. Das hat den Vorteil, dass man (a) den Überblick behält (wer weiß, wie viele Revisionen es geben wird) und (b) lassen sich so Änderungen nachverfolgen. Aktuell ist es nur über Umwege möglich, die Änderungen zwischen Revision 6 und 7 nachzuverfolgen.

**Comment by frostieDE** [comment]
Bitte schnellstmöglich umsetzen, um die weitere Entwicklung sauber mit Git umzusetzen :wink:

**Comment by FPfotenhauer** [comment]
Wir werden das etws anders machen, aber es wird dann nur noch den "current"-Ordner geben.

**Comment by FPfotenhauer** [comment]
Ich habe das jetzt auf zwei Ordner reduziert.
Da dieses Repository abgekoppelt von unserer Entwicklungsumgebung ist, würde ich das auch gerne so lassen. Die Unterschiede in den Scripten sollten so aber angezeigt werden.

**Comment by frostieDE** [comment]
Anstatt der beiden Ordner bieten sich dann Branches an. Diese können dann zum gewünschten Zeitpunkt durch Mergen zusammengeführt werden. Im `develop`-Branch hat man dann die Entwicklungsversion und im `master`-Branch ist jeweils die aktuelle Version enthalten.

**Comment by FPfotenhauer** [comment]
In der eigentlichen Entwicklungsumgebung ist das auch so. Hier werde ich das abgekoppelt auf diese Weise zur Verfügung stellen, bis das eigentiche Repo public geht.
