### ISSUE TITLE
LuPO-Tabellen fehlen für insert_default_data.sql

### ISSUE THREAD

**Issue by frostieDE** [FPfotenhauer/Schild-NRW-DB-Scripte#19]
Die aktuelle Version der insert_default_data.sql (im current-Verzeichnis) ist nicht kompatibel mit dem Datenbankschema, da die LuPO-Tabellen fehlen. 

Das trifft mindestens für MSSQL und MySQL zu. Ich schätze mal, dass die anderen RDMBS auch betroffen sind.

Hier könnte man übrigens mal überlegen, ob man die Konsistenz der Daten mittels CI überprüfen lässt.

**Comment by FPfotenhauer** [comment]
Kann ich nicht nachvollziehen, ich sehe die Lupo-Daten direkt am Beginn.

![2020-02-10_141454](https://user-images.githubusercontent.com/34127980/74153035-f06b3680-4c0f-11ea-9304-b0d88637d3ec.jpg)

**Comment by frostieDE** [comment]
Das Problem ist, dass diese LuPO_*-Tabellen nicht von dem SQL-Skript [current/create_schema.current.mssql.sql](https://github.com/FPfotenhauer/Schild-NRW-DB-Scripte/blob/master/current/create_schema.current.mssql.sql) angelegt werden. Und dann beschwert sich MSSQL-Server zurecht, dass die Tabellen nicht vorhanden sind.

**Comment by FPfotenhauer** [comment]
Ich habe die aktuellen Scripte hochgeladen.
Darin sind die Tabellen enthalten.
