### ISSUE TITLE
running create_schema.current.maria_db.sql leads to plenty errors

### ISSUE THREAD

**Issue by cweikl** [FPfotenhauer/Schild-NRW-DB-Scripte#25]
Having installed MariaDB 10.6.8 (x86 on a Windows 10 Prof. System), I created a Schild database with UTF8mb4_bin collation.
I created a new user with full acces for this db, then I useed this new Schild database. I executed the create_schema.current.maria_db.sql script. This script leads to plenty of error messages. 

Take a look at the screenshots.
![create-schema-current-maria-db-error2](https://user-images.githubusercontent.com/16056720/174435169-f112416d-18e3-492f-9473-8b0bee6d32c2.PNG)
![create-schema-current-maria-db-error](https://user-images.githubusercontent.com/16056720/174435171-203a0855-482e-4c28-ac3d-2e0602fb404b.PNG)

Then I tested it on the same MariaDB platform with the same Connector. I created a new DB and used the following script: Provider=MSDASQL.1;Persist Security Info=False;Data Source=schild_nrw_db

Started Schild, some further table have been created afterwards I started the migration tools an successfully migrated an access db to maria db.

But why does it fail using the mariadb script ?

**Comment by FPfotenhauer** [comment]
The Scrips provided here are not for Schild-NRW-2.0!
We use DBeaver to create new databases with our Scripts for Schild-NRW.3.0.

Installation is described here:
https://wiki.svws.nrw.de/mediawiki/index.php?title=Schild-NRW_Installation#Server-Installation_mit_MySQL-_oder_MariaDB-Datenbank

You can download the Schild-NRW2.0-Scrip there.
Instructions are in german. Sorry.

**Comment by cweikl** [comment]
Danke für Ihre Antwort!
Die Hinweise auf die Revision hatte ich auf die Versionen bezogen - eigentlich klar. 
Evtl. zu Beginn der README.md eingangs darauf hinweisen, dass alle Skripte nur für die Migration zu Schild 3.0 gedacht sind und die Revisionsnummern die verschiedenen Entwicklungsstände dieser Migrationsscripte darstellen.
